plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\ai\\ai agent项目\\五子棋"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]